# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
# theme: minima
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-spaceship

jekyll-spaceship:
  processors:
    - table-processor
    - media-processor
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'


#    - mathjax-processor
#    - plantuml-processor
#    - mermaid-processor
#    - emoji-processor
#    - element-processor

title: "RtW's Wiki"
description: "A mirror for the official Reclaim the Wild's Homebrew Wiki"
logo: "assets/images/rtw.png"

# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/priv_wiki"
url: "https://reclaimthewild.github.io"
# twitter_username: jekyllrb
# github_username:  jekyll

color_scheme: light
aux_links:
  "Contributors":
    - "/priv_wiki/contributor"
  "Tags":
    - "/priv_wiki/tag"
  "Main Website":
    - "https://reclaimthewild.net/"
aux_links_new_tab: false

footer_content: "This is a mirror of the official Reclaim the Wild's wiki and is not in any way affiliated with either Nintendo, or the Reclaim the Wild's team."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

back_to_top: true
back_to_top_text: "Back to top"

exclude:
  - tag/TAG.md
  - contributor/CONTRIBUTOR.md

collections:
  tag:
    output: true
    permalink: /:collection/:name
  contributor:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "tag"
    values:
      title: "Tag index"
      layout: "default"
      excerpt: "List of tagged pages"
  -
    scope:
      path: ""
      type: "contributor"
    values:
      title: "Contributor index"
      layout: "default"
      excerpt: "List of contributors"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
