remote_theme: pmarsceill/just-the-docs

title: "RtW's Wiki"
description: "A mirror for the official Reclaim the Wild's Homebrew Wiki"
logo: "assets/images/rtw.png"

color_scheme: light
aux_links:
  "Main Website":
  - "https://reclaimthewild.net/"
aux_links_new_tab: true

footer_content: "This is a mirror of the official Reclaim the Wild's wiki and is not in any way affiliated with either Nintendo, or the Reclaim the Wild's team."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

back_to_top: true
back_to_top_text: "Back to top"
